blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.EntryDetailView.as_view(), name='detail'),
    path('<int:entry_id>/comment', views.comment, name='comment'),
    path('subscribe/', views.MembershipFormView.as_view(), name='subscribe'),
    path('<int:year>/<int:month>/', views.EntryMonthArchiveView.as_view(
        month_format='%m'), name="archive_month_numeric"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.core import validators


class Entry(models.Model):
    entry_title = models.CharField(max_length=200)
    entry_content = models.TextField()
    pub_date = models.DateTimeField('date published')
    entry_img = models.ImageField(blank=True, validators=[
                                  validators.validate_image_file_extension])

    def __str__(self):
        return self.entry_title


class Comment(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=300)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.comment_text


class Membership(models.Model):
    email_address = models.EmailField(max_length=200)

    def __str__(self):
        return self.email_address

blog/forms.py
from django.forms import EmailInput, ModelForm
from .models import Membership


class MembershipForm(ModelForm):
    class Meta:
        model = Membership
        fields = ['email_address']
        widgets = {
            'email_address': EmailInput(attrs={'class': 'col-form-label col-md-4 col-sm-12 pt-0'}),
        }

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from blog.forms import MembershipForm
from .models import Entry, Membership
from django.utils import timezone
from django.contrib.messages.views import SuccessMessageMixin

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_entry_list'

    def get_queryset(self):
        """Return the last five published posts."""
        return Entry.objects.order_by('-pub_date')[:5]


class EntryDetailView(generic.DetailView):
    model = Entry
    #template_name = 'blog/detail.html'


class EntryMonthArchiveView(generic.dates.MonthArchiveView):
    queryset = Entry.objects.all()
    date_field = 'pub_date'


class MembershipFormView(SuccessMessageMixin, generic.CreateView):
    model = Membership
    form_class = MembershipForm
    success_message = "Thanks for subscribing!"

    def get_success_url(self):
        return reverse('blog:subscribe')


def comment(request, entry_id):
    entry = get_object_or_404(Entry, pk=entry_id)
    comment = ""
    try:
        comment = request.POST['comment'].strip()
        if len(comment) < 5:
            raise ValueError("Less than 5 characters in the comment")
    except (ValueError):
        # Redisplay the post comment form.
        return render(request, 'blog/entry_detail.html', {
            'entry': entry,
            'error_message': "You didn't enter at least 5 characters.",
        })
    else:
        entry.comment_set.create(comment_text=comment, pub_date=timezone.now())
        entry.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('blog:detail', args=(entry.id,)))

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="">

        <title>TB</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'blog/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
        <link href="{% static 'blog/blog.css' %}" rel="stylesheet">
        <link href="{% static 'blog/sticky-footer.css' %}" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <header class="blog-header py-3">
                <div class="row flex-nowrap justify-content-between align-items-center">
                    <div class="col-4 pt-1">
                        <a class="text-muted" href="{% url 'blog:subscribe' %}">Subscribe</a>
                    </div>
                    <div class="col-4 text-center">
                        <a class="blog-header-logo text-dark" href="/">The Blog</a>
                    </div>
                    <div class="col-4 d-flex justify-content-end align-items-center">
                        <!--<a class="text-muted" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
                            <circle cx="10.5" cy="10.5" r="7.5"></circle>
                            <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
                        </svg>
                    </a>
                        <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>-->
                    </div>
                </div>
            </header>
            <!-- <div class="">
                <script type="text/javascript" src="https://files.coinmarketcap.com/static/widget/coinMarquee.js"></script>
                <div id="coinmarketcap-widget-marquee" coins="1,1027,11212,5426,2010" currency="EUR" theme="light" transparent="true" show-symbol-logo="true"></div> -->
            </div>
        </div>

        {% block content %}{% endblock %}

        <footer class="blog-footer footer">
            <p>All rights reserved © 2021.</p>
            <p>
                <a href="#">Back to top</a>
            </p>
        </footer>

        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script>
            window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')
        </script>
        <script src="{% static 'blog/popper.min.js' %}"></script>
        <script src="{% static 'blog/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/holder.min.js' %}"></script>
        <script>
            Holder.addTheme('thumb', {
                bg: '#55595c',
                fg: '#eceeef',
                text: 'Thumbnail'
            });
        </script>
    </body>

</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
<div class="container">

    <!-- /.blog-post detail informaton -->
    <div class="blog-post">
        <h2 class="blog-post-title">{{ entry.entry_title }}</h2>
        <p class="blog-post-meta">{{ entry.pub_date }}</p>
        <img class="img-fluid" src="{% static 'blog/media/3.jpg' %}" width="600"><br><br>
        <p>{{ entry.entry_content }}</p>
    </div><!-- /.blog-post -->

    <!-- /.blog-post comments section -->
    <p>comments:</p>
    <ul class="list-group list-group-flush">
        {% for comment in entry.comment_set.all|dictsortreversed:"pub_date" %}
        <li class="list-group-item">
            <span class="blog-post-meta">{{ comment.pub_date }}</span><br>
            {{ comment.comment_text }}
        </li>
        {% endfor %}
    </ul>

    <!-- /.blog-post new comment form -->
    <div class="form-group">
        <form action="{% url 'blog:comment' entry.id %}" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="col-form-label col-sm-12 pt-0">Comment on this post below:</legend>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <textarea class="form-control" name="comment" id="comment{{ forloop.counter }}" rows="5"></textarea>
            </fieldset>
            <input class="btn btn-primary mb-2" type="submit" value="Comment">
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/entry_archive_month.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <br><br>
        <ul class="list-group list-group-flush">
            {% for entry in object_list %}
                <li class="list-group-item"><a href="{% url 'blog:detail' entry.id %}">{{ entry.pub_date|date:"F j, Y" }}: {{ entry.entry_title }}</a></li>
            {% endfor %}
        </ul>

        <p>
            {% if previous_month %}
                <a href="{% url 'blog:archive_month_numeric' previous_month.year previous_month.month %}">Previous Month: {{ previous_month|date:"F Y" }}</a>
            {% endif %}
            {% if next_month %}
                <a href="{% url 'blog:archive_month_numeric' next_month.year next_month.month %}">Next Month: {{ next_month|date:"F Y" }}</a>
            {% endif %}
        </p>
    </div>
{% endblock %}

blog/templates/blog/entry_detail.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="container">

        <!-- /.blog-post detail informaton -->
        <div class="blog-post">
            <h2 class="blog-post-title">{{ entry.entry_title }}</h2>
            <p class="blog-post-meta">{{ entry.pub_date }}</p>
            <img class="img-fluid" src="{% static 'blog/media/' %}{{ entry.entry_img.name }}" width="600"><br><br>
            <p>{{ entry.entry_content }}</p>
        </div><!-- /.blog-post -->

        <!-- /.blog-post comments section -->
        <p>comments:</p>
        <ul class="list-group list-group-flush">
            {% for comment in entry.comment_set.all %}
                <li class="list-group-item">
                    <span class="blog-post-meta">{{ forloop.counter }} - {{ comment.pub_date }}</span><br>
                    {{ comment.comment_text }}
                </li>
            {% endfor %}
        </ul>

        <!-- /.blog-post new comment form -->
        <div class="form-group">
            <form action="{% url 'blog:comment' entry.id %}" method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="col-form-label col-sm-12 pt-0">Comment on this post below:</legend>
                    {% if error_message %}<p style="color:lightcoral"><strong>{{ error_message }}</strong></p>{% endif %}
                    <textarea class="form-control" name="comment" id="{{ entry.id }}" rows="5" required></textarea>
                </fieldset>
                <input class="btn btn-primary mb-2" type="submit" value="Comment">
            </form>
        </div>
        <br>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="container">

        <!-- /.blog-post jumbo section -->
        <div class="jumbotron p-3 p-md-4 text-white rounded bg-dark">
            <div class="col-md-8 px-0">
                {% if latest_entry_list %}
                    <h1 class="display-4 font-italic">{{ latest_entry_list.first.entry_title }}</h1>
                    <p class="lead my-3">{{ latest_entry_list.first.entry_content|truncatechars:70 }}</p>
                    <p class="lead mb-0"><a href="{% url 'blog:detail' latest_entry_list.first.id %}" class="text-white font-weight-bold">Continue reading...</a></p>
                {% endif %}
            </div>
        </div>

        <!-- /.blog-post highlighted section -->
        <div class="row mb-2">
            {% if latest_entry_list %}
                <div class="col-md-6">
                    <div class="card flex-md-row mb-4 box-shadow h-md-250">
                        <div class="card-body d-flex flex-column align-items-start">
                            <!--<strong class="d-inline-block mb-2 text-primary">World</strong>-->
                            <h3 class="mb-0">
                                <a class="text-dark" href="{% url 'blog:detail' latest_entry_list.1.id %}">{{ latest_entry_list.1.entry_title|truncatechars:30 }}</a>
                            </h3>
                            <div class="mb-1 text-muted">{{ latest_entry_list.1.pub_date }}</div>
                            <p class="card-text mb-auto">{{ latest_entry_list.1.entry_content|truncatechars:70 }}</p>
                            <a href="{% url 'blog:detail' latest_entry_list.1.id %}">Continue reading</a>
                        </div>
                        <img class="card-img-right flex-auto d-none d-xl-block" width="200" data-src="holder.js/200x250?theme=thumb" alt="Card image cap" src="{% static 'blog/media/' %}{{ latest_entry_list.1.entry_img.name }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card flex-md-row mb-4 box-shadow h-md-250">
                        <div class="card-body d-flex flex-column align-items-start">
                            <!--<strong class="d-inline-block mb-2 text-success">Design</strong>-->
                            <h3 class="mb-0">
                                <a class="text-dark" href="{% url 'blog:detail' latest_entry_list.2.id %}">{{ latest_entry_list.2.entry_title|truncatechars:30 }}</a>
                            </h3>
                            <div class="mb-1 text-muted">{{ latest_entry_list.2.pub_date }}</div>
                            <p class="card-text mb-auto">{{ latest_entry_list.2.entry_content|truncatechars:70 }}</p>
                            <a href="{% url 'blog:detail' latest_entry_list.2.id %}">Continue reading</a>
                        </div>
                        <img class="card-img-right flex-auto d-none d-xl-block" width="200" data-src="holder.js/200x250?theme=thumb" alt="Card image cap" src="{% static 'blog/media/' %}{{ latest_entry_list.2.entry_img.name }}">
                    </div>
                </div>
            {% endif %}
        </div>
    </div><!-- /.container-->

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8 blog-main">
                <h3 class="pb-3 mb-4 font-italic border-bottom">
                    From the Firehose
                </h3>

                <!-- /.blog-post new posts render -->
                {% if latest_entry_list %}
                    {% for entry in latest_entry_list|slice:"3:" %}
                        <div class="blog-post">
                            <h2 class="blog-post-title"><a style="color: inherit;" href="{% url 'blog:detail' entry.id %}">{{ entry.entry_title|truncatechars:30 }}</a></h2>
                            <p class="blog-post-meta">{{ entry.pub_date }}</p>
                            <p>{{ entry.entry_content|truncatechars:300 }}</p>
                            <p><a href="{% url 'blog:detail' entry.id %}">Continue reading</a></p>
                        </div><!-- /.blog-post -->
                    {% endfor %}
                {% else %}
                    <p>No posts are available.</p>
                {% endif %}
                <!-- /.blog-post -->

                <!--<nav class="blog-pagination">
                <a class="btn btn-outline-primary" href="#">Older</a>
                <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
            </nav>-->

            </div><!-- /.blog-main -->

            <aside class="col-md-4 blog-sidebar">
                <div class="p-3 mb-3 bg-light rounded">
                    <h4 class="font-italic">About</h4>
                    <p class="mb-0">Blog for news, updates and stuff</p>
                </div>

                <div class="p-3">
                    <h4 class="font-italic">Archives</h4>
                    <ol class="list-unstyled mb-0">
                        <li><a href="{% url 'blog:archive_month_numeric' 2021 11 %}">Nov 2021</a></li>
                        <li><a href="{% url 'blog:archive_month_numeric' 2021 10 %}">Oct 2021</a></li>
                    </ol>
                </div>

                <div class="p-3">
                    <h4 class="font-italic">Elsewhere</h4>
                    <ol class="list-unstyled">
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">YouTube</a></li>
                    </ol>
                </div>
            </aside><!-- /.blog-sidebar -->

        </div><!-- /.row -->

    </main><!-- /.container -->
{% endblock %}

blog/templates/blog/membership_form.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <br><br>
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary mb-2" value="Save">
        </form>
    </div>
{% endblock %}